### ISSUE TITLE
Maintain a complete, up-to-date list of unimplemented parts of the Checked C specification

### ISSUE THREAD

**Issue by mattmccutchen-cci** [checkedc/checkedc-clang#1193]
In CCI's work with the Checked C compiler, we've often found that the compiler didn't behave as described in the specification, but it has been a hassle for us to find information about exactly what is and is not implemented.  Many of the things that aren't implemented are described by issues in this issue tracker, but those aren't always easy to find.  Often, we've resorted to testing the compiler's behavior ourselves on various examples.

There should be a centralized list of unimplemented parts of the specification (with links to corresponding issues, if any) that is kept complete and up to date.  It looks like [this wiki page](https://github.com/microsoft/checkedc-clang/wiki/Implementation-roadmap-and-status) may be intended to be that list, but it doesn't look like it goes to the level of detail I'm asking for.  For example, I ran across #40 yesterday, and it's unclear to me where (if at all) #40 is covered on the wiki page.

One approach would be to add the information about implementation status to the specification itself.  If that doesn't offend your sensibilities too much, it would make it much easier to ensure over time that the status of all parts of the specification is documented.

**Comment by dtarditi** [comment]
The spec has been [updated](https://github.com/checkedc/checkedc/releases/tag/v1.0) so that it separates what has been implemented from what is on the future roadmap.  This should resolve this issue.
