### ISSUE TITLE
Feature Request: Preprocessor to Remove CheckedC notation

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [checkedc/checkedc-clang#555]
Some folks have expressed interest in using CheckedC-Clang during development but then compiling for production under a different compiler. They would like to be able to use preprocessor macros to remove the CheckedC notations automatically, so that they can run a different compiler without extensive further edits to their code.

For some of our notation, this is straightforward: just `#define itype(foo)  ` to be empty for `itype`, `count`, `byte_count`, `Dynamic_bounds_cast`; for other parts, such as `:`, more complicated. Checked types will have to be converted back to their unchecked forms. The aspects that will be the most difficult are the punctuation `<` and `>` in checked types and `:`.  They present a problem because they are not valid characters in an identifier and the first argument to a `#define` must be an identifier. 

One way I can imagine getting around the punctuation issue is, for example, replacing `:` with `_COLON` (or some other valid identifier) in the source code and then either defining `_COLON` to blank or to `:` inside a preprocessor if statement. No idea what a good identifier name would be, given the extremely frequent use of these punctuation characters in checked code.

**Comment by dtarditi** [comment]
This has been implemented.
