### ISSUE TITLE
Linux release build in Releases?

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [checkedc/checkedc-clang#588]
Any chance a Linux release build could be made available in Releases? I'd like to use this on a project I'm working on with some collaborators and having to build the compiler is a bit more of a barrier to entry than I'd like to impose.
Thanks!

**Comment by dtarditi** [comment]
Which version/flavor of Linux are you interested in?

**Comment by dtarditi** [comment]
I've upgraded our internal Linux build machine to Ubuntu 18.04 LTS, in preparation for supporting a Linux build.   LLVM has separate installs for different LTS versions of Ubuntu, so I'm guessing we'll need a separate install per LTS version.

**Comment by master-q** [comment]
I also want to use this project on Debian GNU/Linux. Because I'm trying to use https://github.com/Microsoft/checkedc-parson.
The releases are better, but some ***documents explaining Linux build process*** is also useful.

**Comment by mgrang** [comment]
> I also want to use this project on Debian GNU/Linux. Because I'm trying to use https://github.com/Microsoft/checkedc-parson.
> The releases are better, but some _**documents explaining Linux build process**_ is also useful.

Here are the instructions to build the Checked C Clang compiler: https://github.com/microsoft/checkedc-clang/blob/master/clang/docs/checkedc/Setup-and-Build.md

**Comment by dtarditi** [comment]
We support Ubuntu releases now :).
